### ISSUE TITLE
Historical and projected indices by time for various regions, for BU and POP

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/2BURP#101]

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/8ecce5f4-14f3-4098-a2c1-1cfd47233c69)

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/0f3e4a17-4c53-4328-ad88-16e0e92a4a78)
![image](https://github.com/user-attachments/assets/eace40a2-e220-4ee9-a46a-cc0a3bc06cf1)

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/f23fe7c3-929a-41cb-84d1-b6114bcc0cb8)
![image](https://github.com/user-attachments/assets/38c25fe7-6430-4cd9-9a60-fee060bac67a)

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/eb3d1dd1-5d05-42b2-bbb3-b7a9644572e1)
![image](https://github.com/user-attachments/assets/d563591d-292f-4e37-81f7-76706b9f5bf9)

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/2595d0dd-6f79-4dcf-8616-773b93fbe66f)

**Comment by jipclaassens** [comment]
[Population_per_ClaimRegion_China.xlsx](https://github.com/user-attachments/files/17517161/Population_per_ClaimRegion_China.xlsx)
