### ISSUE TITLE
Run doen met veel hogere pop maxima. Hoe beinvloedt dit pop densities?

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/2BURP#102]
- densities on land per DoU per jaar
- pop per DoU per jaar
- areal per DoU per jaar

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/fcccdeae-f7cd-4c8f-8fee-59a00e2ba246)
![image](https://github.com/user-attachments/assets/1fca9bb3-c732-4881-a7e2-e1d80d744db2)

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/9f72c557-cfe6-4bdc-98c8-a268cca5413d)
![image](https://github.com/user-attachments/assets/7c7ba341-93fd-4fb6-844f-13a846c4d338)

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/f76b015e-9a96-42bb-a2a4-c4724fe4c597)
![image](https://github.com/user-attachments/assets/f3f79cd2-acb4-4c3d-8644-b6e665be82b7)

**Comment by jipclaassens** [comment]
Oftewel, door de limieten veel te verhogen, worden de densities juist lager! 

![image](https://github.com/user-attachments/assets/1313f447-0e99-4ae4-b7e4-4b99aab6a854)

**Comment by jipclaassens** [comment]
[20241025 Analyse Unlimited Pop Increases.xlsx](https://github.com/user-attachments/files/17520134/20241025.Analyse.Unlimited.Pop.Increases.xlsx)
