### ISSUE TITLE
Run model is only Proportional reductions, and only Absolute reductions

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#103]
and in shrinking county and growing country

**Comment by cjacobscrisioni** [comment]
Ran for all continents with 1% proportional / 4% absolute, and vice versa, then compared with 2.5% balanced. Main conclusion: "relatively more absolute reductions leads to more urban population, higher densities in cities, but faster abandonment."

**Comment by cjacobscrisioni** [comment]
Population density results for Africa 

2.5% balanced:
![Image](https://github.com/user-attachments/assets/4c968141-0c4d-44fa-b931-ca6438513564)

1% proportional, 4% absolute:
![Image](https://github.com/user-attachments/assets/2e255f68-99da-46d9-9aef-480c0487be93)

4% proportional, 1% absolute:
![Image](https://github.com/user-attachments/assets/d7aa0f01-d51f-40b0-84d8-3161d081eb71)
