### ISSUE TITLE
Rethink reduction procedure: add an additional mechanism to ensure the regional absolute reduction is the X% change.

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#105]
- keep absolute and proportional as is
  - add an additional mechanism to ensure the regional absolute reduction is the X% change.

Related #106

**Comment by jipclaassens** [comment]
check effect of absolute/proportional first? #103

**Comment by MaartenHilferink** [comment]
Given population $P_i$ at land unit i, total population $ P := \sum_i P_i $ and absolute reduction target $r \cdot P$ with $ r \in \(0...1)$

without loss of generality, assume that the $P_i$'s are ascending values, i.e. $P_i \le P_j <=> i \le j $

Find a cutoff value $z$ such that $r \cdot P \= \sum_i \min(P_i, z)$

**Comment by jipclaassens** [comment]
Niet meer nodig, want opgelost in #106
