### ISSUE TITLE
Check effect van Mollweide impl tov Latlong impl

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#112]

**Comment by cjacobscrisioni** [comment]
Managed to generate indicators, but results are quite divergent. Possibly because the Add Claim reduction factor was set higher in the reference lat-lon runs.

**Comment by cjacobscrisioni** [comment]
Confirmed: i ran the model with a version that did not store add claim reduction factor specifics in the filesuffix. The change from 2 to 1 was simultaneous with that change to the filesuffix. I will run the MW version for Europe with a acr of 2 for comparison.

**Comment by cjacobscrisioni** [comment]
Running the 2.5% balanced scenario with a reduction factor of 2 (assuming that is what I ran prior). In the Mollweide version we have substantial differences, with much more suburbanisation and lower urban densities:

![ln_area_Europe_v8_PopIPRR-0 025_PopIARR-0 025_PopShareNewBU-1](https://github.com/user-attachments/assets/75a69e9b-5282-4c67-9908-1bc9ce7e5027)
![ln_area_Europe_v8_PopIPRR-0 025_PopIARR-0 025_PopShareNewBU-1_AddClaimReducF-2_54009](https://github.com/user-attachments/assets/be2eb28a-709e-498c-b8e0-9e387997a102)
![pop_Europe_v8_PopIPRR-0 025_PopIARR-0 025_PopShareNewBU-1](https://github.com/user-attachments/assets/3342afd3-01f8-4d65-861e-69bc9771005a)
![pop_Europe_v8_PopIPRR-0 025_PopIARR-0 025_PopShareNewBU-1_AddClaimReducF-2_54009](https://github.com/user-attachments/assets/add1f7ed-7902-4507-94d5-516b24283e19)
![popdens_Europe_v8_PopIPRR-0 025_PopIARR-0 025_PopShareNewBU-1](https://github.com/user-attachments/assets/f3e87a2b-c281-4e95-8d65-4421029c82ea)
![popdens_Europe_v8_PopIPRR-0 025_PopIARR-0 025_PopShareNewBU-1_AddClaimReducF-2_54009](https://github.com/user-attachments/assets/219a3444-4b99-4b6f-831d-012b20823026)
![abandoned_Europe_v8_PopIPRR-0 025_PopIARR-0 025_PopShareNewBU-1](https://github.com/user-attachments/assets/e50422d1-7fa1-4b34-9eca-df4728f710ee)
![abandoned_Europe_v8_PopIPRR-0 025_PopIARR-0 025_PopShareNewBU-1_AddClaimReducF-2_54009](https://github.com/user-attachments/assets/6c3eb07d-c445-4f22-903e-4c8b7f9681bd)

**Comment by cjacobscrisioni** [comment]
On the plus side, less abandonment.

**Comment by jipclaassens** [comment]
> On the plus side, less abandonment.

This is what we expected right? Less spreadout pop in the beginning due to resampling of MW to WGS conversion of pop rasters?
