### ISSUE TITLE
/Preprocessing/Calculate_GridDistances/Network/Length gives many null values in Australia & Oceania

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/2BURP#117]
Item throws 882,830 null values. Defined as dependent on the Lat/Lon coordinates of grid cells through dx and dy. The items dx and dy also have 882,830 null values. 

Null values are problematic because non-null values are needed for the subsequent dijkstra() operation.

Potentially related: repeated error notifications "gdal Failure(1): Point outside of projection domain"  while computing the above items.

The issue does not pop up in Europe, Africa or South America. Maybe related to the date border?

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/9eb9f05a-6a4f-41e8-bebf-9f51be6ca66d)

de f1 en f2 punten liggen idd op projectiegrens.

**Comment by jipclaassens** [comment]
conversie van Mollweide grid centroid coordinaten naar Latlong geeft 220,982 nulls, van de 31.5 miljoen.

`Preprocessing/Calculate_GridDistances/NodeSet/geometry`
