### ISSUE TITLE
Zoek verklaring voor dip in abandonement 2030-2050

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#118]
![Image](https://github.com/user-attachments/assets/23e92da2-8733-45a5-a78b-9cf4bc388743)

**Comment by jipclaassens** [comment]
Voorbeeld van een abandoned cell in 2020 en de voorgaande originele pop ontwikkeling.

![Image](https://github.com/user-attachments/assets/53e97282-120c-4cb5-b1a1-39506fded573)

**Comment by jipclaassens** [comment]
We zien jaar op jaar krimp, geen abandonment in 2030-2040-2050, en een golf in 2060. 
nth_element round off neemt toe tussen 2030 en 2050, en af in 2060.

suitabilty weighted reductions trekken groot deel van de weinig bevolkte cell leeg. maar vervolgens houdt het mechanisme de pop heel vast, door round-off. Tipping point in 2060?

Maarten stelt voor de controleren of de dip ook voorkomt in Afrika. Is dit een gevolg van krimp van pop + groei van BU?

**Comment by cjacobscrisioni** [comment]
Met nieuwe schaling (0.9 poprsuitscale, autoresolve) lijkt is de dip niet meer in een dip. 
![image](https://github.com/user-attachments/assets/4cf64a0c-b17d-410b-85a9-0730500b2019)
