### ISSUE TITLE
Calculate dynamic distance to urban centres

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#16]
- distance to nearest urban centre within 50km (decided 30-01-2024)
- based on resistance? Add info about water/mountains/etc.

Check the importance in calibration
- calc distance in 2000, then check 2020.

We need settlements in 2000 and 2020.

**Comment by cjacobscrisioni** [comment]
Settlement boundaries 2000 are downloadable here: https://surfdrive.surf.nl/files/index.php/s/k0vz4fuG0s9vM7s

Settlement boundaries 2020 are already available in the networkmodel_world configuration

**Comment by jipclaassens** [comment]
dependant of succes of #29

**Comment by jipclaassens** [comment]
dependant of #28

**Comment by jipclaassens** [comment]
Add to suitability
/Preprocessing/GridDistances/Y2020/Grid_costs_atleast_to
