### ISSUE TITLE
Refine grid dist calculation

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/2BURP#28]
Grid dist calculations  
- [x] Determine if projection should be LatLong {earlier version stated WebMercator)
- [x] Ideally are based on a % within water grid, not 0/1.
- [x] Incorporate country borders (through a sizeable penalty, see https://forobs.jrc.ec.europa.eu/gam/sources) 
- [x] Swap settlement centroids for settlement polygons (to account for multiple acceptable startpoints in larger settlements)

**Comment by cjacobscrisioni** [comment]
Adjusted network-based calculations, swapping start- and endpoints. See d450536..feedfc1. Very good performance now.

**Comment by MaartenHilferink** [comment]
Webmercator:
As all other calculation are done in WGS84 (LatLong) (with the exception of connect to road vector data, which is done in WebMercator), I think this operation should also be done in  WGS84; for this, using latitude specific aspect ratio's has been filed as feature request at https://github.com/ObjectVision/GeoDMS/issues/673

**Comment by cjacobscrisioni** [comment]
> Webmercator: As all other calculation are done in WGS84 (LatLong) (with the exception of connect to road vector data, which is done in WebMercator), I think this operation should also be done in WGS84; for this, using latitude specific aspect ratio's has been filed as feature request at [ObjectVision/GeoDMS#673](https://github.com/ObjectVision/GeoDMS/issues/673)

@MaartenHilferink can you already share the latitude specific aspect ratio's / formula? So I can include them in the network-based approximation.

**Comment by jipclaassens** [comment]
Concerning borders. @MaartenHilferink is working on something to include districts (https://github.com/ObjectVision/GeoDMS/issues/673)

**Comment by MaartenHilferink** [comment]
@cjacobscrisioni 
- See progress in https://github.com/ObjectVision/GeoDMS/issues/673 for latitude_specific variants, which are implemented in https://github.com/ObjectVision/GeoDMS/releases/tag/v14.15.3  Zonal barriers on the way and planned to be in v14.15.4.
- formula for lat-long; factor := cos(latitude * pi / 180.0)
- - distance between two north-south rasters: original
- - distance between two east-west rasters: original * factor
- - distance between two diagonally connected cells: original * sqrt(1+factor* factor)
- see lines 310 jo 317 in https://github.com/ObjectVision/GeoDMS/releases/tag/v14.15.3
- I intend to replace cos(latitude) by PJ_FACTORS ::meridional_scale resulting from proj_factors, but this hasn't been working yet.

**Comment by MaartenHilferink** [comment]
I'll add examples in /Preprocessing/GridDists/AccessGrids_grid/gggg/xxxx that refer to 

`/SourceData/RegionalUnits/Countries/per_grid`

to determine zonal boundaries and use 25f as Zonal boundary barrier.

**Comment by MaartenHilferink** [comment]
See https://github.com/ObjectVision/GeoDMS/releases/tag/v14.15.4 and latest commit of 2BURP

**Comment by cjacobscrisioni** [comment]
Tested all implemented versions, all working perfectly now. Still need to decide whether to stick with the network-based variant or one of the costs versions (will depend on calibration tests as well). Latitude-corrected versions show sizeable differences even in Denmark, indicating the relevance of doing so. Thanks!
