### ISSUE TITLE
Create calibration files per continent

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#35]

**Comment by cjacobscrisioni** [comment]
Adaptations:
- added a parameter with the relevant geometry in the latlong sets (linked to studyareas)
- added the requisite that grid cells in the compacted domain are inside the study area geometry parameter
- stored unlinked sourcedata files to study-area specific folders (saves recalculating for every study area swap)

**Comment by cjacobscrisioni** [comment]
Pushed, @jipclaassens , please make sure to pull most recent changes

**Comment by cjacobscrisioni** [comment]
Reopened ... Asian domain spans all longitudes (because a minor part of Eastern Russia is on the western half). Causes inefficiencies in the distance grids, maybe better to execute the connect only on the compacteddomain subset.

**Comment by cjacobscrisioni** [comment]
> Reopened ... Asian domain spans all longitudes (because a minor part of Eastern Russia is on the western half). Causes inefficiencies in the distance grids, maybe better to execute the connect only on the compacteddomain subset.

Already executed in the compacteddomain. Currently falling back to a direct connect() on the original shapefile geometry instead.

**Comment by cjacobscrisioni** [comment]
Temporarily dropped the gd_ type variable (based on network-based griddist approximation) because of persistent memory allocation issues. The problem seems to be with continents that are partially on the far west side of the projection, and then partially also on the far east side. 

Annoying, but not critical, if from calibration with available sets follows that (as expected) the gd_ type variable is inferior to the gc_ type. The gc_ type is computable through lat_lon corrected griddist() functions.

**Comment by cjacobscrisioni** [comment]
Fix for the issues with gd_ would be to catch it, artificially connect the far wests with the far easts, and drop out the uncovered middle grounds.

**Comment by cjacobscrisioni** [comment]
Asia + Australia / Oceania still cause crashes. Need to unlink gd griddist results.

**Comment by jipclaassens** [comment]
Wat crasht er precies? Kun je het wat specificeren? Evt met screenshot en pad. Dan kan Maarten het fixen.

**Comment by cjacobscrisioni** [comment]
Crash als ik /Analysis/Calibration/Export_DataForCalibration/result probeer te updaten voor bovengenoemde continenten. Eerst extreem veel emptyworkingmemory procedures, dan een volledig vaste pc. Daarna harde crash + GeoDMSQTGui stopped working bericht, verder geen info.

**Comment by cjacobscrisioni** [comment]
Ik heb nu geprobeerd de operatie te herhalen door een warped grid te maken waarbij het continent volledig wordt verplaatst naar het oostelijk of westelijk halfrond. Nog steeds zware load.

**Comment by cjacobscrisioni** [comment]
Het probleem lijkt al te beginnen bij de grote grid definitie voor de genoemde continenten. Bijv harde crash als ik /Preprocessing/GridDists/grid/as_id aanroep (GeoDMSQTgui stopped working).

**Comment by cjacobscrisioni** [comment]
Performed a number of optimisations on the griddists calculations (mostly to cut down the nr of origins) but I keep getting hard crashes for certain in Australia / Oceania. Below error message occurs when updating grid dist measure, I tested /Preprocessing/GridDists/AccessGrids_grid/villages/costsgrid_maximp and /Preprocessing/GridDists/AccessGrids_grid/villages/costsgrid_zonal_untiled_maximp_latitude_specific

![image](https://github.com/ObjectVision/2BURP/assets/144823297/bb3113c3-e597-4788-a6d3-690ee42003c4)

**Comment by cjacobscrisioni** [comment]
the /Preprocessing/GridDists/AccessGrids_grid/villages/impedances element takes very long because the continent grid is overdimensioned. This grid stretches from -180 to +180 because bits of the continent are present in the western and eastern hemisphere. Can we somehow limit grid sizes that are on both sides of the world?

**Comment by jipclaassens** [comment]
Thanks, we are working on it!

**Comment by jipclaassens** [comment]
This container a null-coordinate for fiji
`/Preprocessing/GridDists/load_settlements/Australia_Oceania/infile/geometry`

After fix from @MaartenHilferink this is now the error:
![image](https://github.com/ObjectVision/2BURP/assets/48675272/ccea6fd1-ed87-4a76-a25e-b1bdce9cf63d)

**Comment by jipclaassens** [comment]
So, @cjacobscrisioni where is the .shp created? It should not contain null-coordinates

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/2BURP/assets/48675272/3a2d9173-849b-4f77-beae-8df41d75b311)

**Comment by jipclaassens** [comment]
QGIS can visualise it okay, it probably skips the 'nan' coordinate, but it is there. And GeoDMS doesn't like it. In 

![image](https://github.com/ObjectVision/2BURP/assets/48675272/1f214925-609d-4add-8155-9d940cbabd3a)

**Comment by jipclaassens** [comment]
Longterm solution is discussed here: https://github.com/ObjectVision/GeoDMS/issues/721

Short-term work-around idea:
- skip null-coordinates, and connect the correct coordinates.

**Comment by eoudejans** [comment]
Using tool DB Browser for SQLite the definition of **ESRI:54009** can be found in Table projected_crs as:

> PROJCS["World_Mollweide",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Mollweide"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",0.0],UNIT["Meter",1.0]]

**Comment by eoudejans** [comment]
Geodms script to create an arc for the boundaries of Mollweide:

```cpp
	parameter<int32> n :=   90i;
	parameter<int32> s :=  -90i;
	parameter<int32> e :=  180i;
	parameter<int32> w := -180i;
	
	unit<int32> y_range := range(int32, s, n+1i) {
		attribute<int32> sn := id(.);
		attribute<int32> ns := Reverse(sn);
		attribute<geography/EPSG_4326> sw_nw := point_xy(float64(const(w, .)), float64(sn), geography/EPSG_4326);
		attribute<geography/EPSG_4326> nw_sw := point_xy(float64(const(w, .)), float64(ns), geography/EPSG_4326);
		attribute<geography/EPSG_4326> ne_se := point_xy(float64(const(e, .)), float64(ns), geography/EPSG_4326);
	}
	
	unit<int32> x_range := range(int32, w, e+1i) {
		attribute<int32> we := id(.);
		attribute<int32> ew := Reverse(we);
		attribute<geography/EPSG_4326> se_sw := point_xy(float64(ew), float64(const(s, .)), geography/EPSG_4326);
		attribute<geography/EPSG_4326> ne_nw := point_xy(float64(we), float64(const(n, .)), geography/EPSG_4326);
		attribute<geography/EPSG_4326> nw_ne := point_xy(float64(we), float64(const(n, .)), geography/EPSG_4326);
	}

	unit<uint32> points_all := union_unit(y_range, x_range, y_range, x_range) {
		attribute<geography/EPSG_4326> points := union_data(., y_range/sw_nw, x_range/nw_ne, y_range/ne_se, x_range/se_sw);
		parameter<geography/EPSG_4326> geometry (arc) := points2sequence(points);
		parameter<geography/ESRI_54009> geometry_mw (arc) := convert(geometry, geography/ESRI_54009);
	}
```

Result of item **/points_all/geometry_mw**:
![image](https://github.com/ObjectVision/2BURP/assets/96182097/ffa2f417-ef9e-41df-9676-8a078a9e6da3)

**Comment by eoudejans** [comment]
Super zoom of Square Fiji:
![image](https://github.com/ObjectVision/2BURP/assets/96182097/c13adb12-7cad-4b46-9b6b-160e9fbc13a4)

**Comment by MaartenHilferink** [comment]
See also: https://github.com/ObjectVision/GeoDMS/issues/721

**Comment by cjacobscrisioni** [comment]
All calibration files generated and shared today (first iteration)

More iterations foreseen with reduced calib file sizes as we are gradually discarding variables

**Comment by cjacobscrisioni** [comment]
Changed naming of variables so they are more intuitive; dropped references to accessibility to centres, as centres seem inferior to degrees of urbanisation when explaining static presence of built-up land.

**Comment by cjacobscrisioni** [comment]
Definite calibration files are presently available here: https://surfdrive.surf.nl/files/index.php/s/Sdk8TBHxPJBgcuQ . These will need to be filed later for future reference.
