### ISSUE TITLE
consider scaling max population and increase rates according to raster-cell size.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/2BURP#36]
See also: https://www.frontiersin.org/articles/10.3389/fphy.2022.861678/full

dimentionality of population is 1.8 or 1.9 ? Thus 100.000 for a km2 is sqrt(0.5)^1.8 * 100.000 = 0.5^0.9 * 100.000 = 53.588 or sqrt(0.5)^1.9 * 100.000 = 51.763 for latitude=60[degs] and not 50.000

**Comment by jipclaassens** [comment]
Decided that for this case we do ignore it. 

Neighbourhood calculations are different in Norway compared to the equator.
