### ISSUE TITLE
Implement IntegrityCheck per functional area that full saturation of non-non-residential built-up area can meet the additional population claim

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#42]

**Comment by MaartenHilferink** [comment]
The added FeasibilityCheck now is false for obvious reasons outside a StudyArea.

![Image](https://github.com/ObjectVision/2BURP/assets/2284361/125ff0d0-7494-429d-9bcf-e91bab4851fc)

To seriously monitor IntegrityChecks, we'll have to aggregate only the relevant (i.e. in the StudyArea) results before commiting any allocation result that depends on any of such checks.

**Comment by jipclaassens** [comment]
![Image](https://github.com/ObjectVision/2BURP/assets/48675272/7db7be17-9149-4071-9b89-5b444e895b38)

**Comment by jipclaassens** [comment]
I added the integrity check to the cutting line; that should be fine, right @MaartenHilferink ?
