### ISSUE TITLE
Rethink reduction rates, explore empirics?

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#48]
Maybe two approaches for regions with and without shrinkage

**Comment by MaartenHilferink** [comment]
reduction rate := max_elem(5%, regional reduction)
applicable on both the absolute and the relative reduction, thus twice with up to 10% reduction when regional reductio is less than 5%

**Comment by jipclaassens** [comment]
Now implemented as:
reduction rate := max_elem(2.5%, 2 * regional reduction)
