### ISSUE TITLE
Create global TRI grid

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/2BURP#52]
Currently TRI is generated through an unlinked, study area specific generation process. 

This can only be replicated with a ~100GB file, or by sharing all study area specific versions. This is inefficient. 

Would it be possible to generate the used TRI grid globally as a one-off and then include that in the process instead of the study area specific versions?

**Comment by jipclaassens** [comment]
Yes, calculating as we speak.

**Comment by jipclaassens** [comment]
- Africa/Europe/South America work fine with 64gb RAM
- Oceania/Asia/North America, no bueno -> crash.

If we do need this layer, we need some clever performance fix. Tile it. Or a more powerful computer.

@cjacobscrisioni  @MaartenHilferink

**Comment by MaartenHilferink** [comment]
Oceania: 175 GB peak, 58 seconds, by a combination of #64, and #52.

![image](https://github.com/ObjectVision/2BURP/assets/2284361/9deb8099-e3e3-437d-9939-d94454eaa4d4)

**Comment by jipclaassens** [comment]
North America, 4 min + 200gb, including writhing to tif.

**Comment by jipclaassens** [comment]
All continent files are in the SD/surfdrive. @MaartenHilferink can you explain on Monday how I should implement the raster_merge?

**Comment by jipclaassens** [comment]
TRI World staat nu in surfdrive SD. En dit wordt al aangeroepen in de maak calibratiefiles. @cjacobscrisioni
