### ISSUE TITLE
Unexpected built-up distribution during modelling, randomise?

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/2BURP#54]
Prior built-up is used as a constraint, and dynamic suitability factors are being used, but density plots show staggered increases in built-up land.

Density plot first model version (Nigeria)
![image](https://github.com/ObjectVision/2BURP/assets/144823297/146e57d0-ef6f-42ef-a77f-9d9f6a431b0b)

Density plot second model version (Nigeria)
![image](https://github.com/ObjectVision/2BURP/assets/144823297/aff0c8f0-1ab4-4b41-a5c7-a074c32d04e0)

Difference between first and second model versions (Nigeria) show marked improvements, but still unexpected staggering:
![image](https://github.com/ObjectVision/2BURP/assets/144823297/6eebb32d-f18d-43da-8da1-68d09ce6ed4b)

**Comment by MaartenHilferink** [comment]
@Chris: 
1. density plots": Do the area under each curve (the integral) represent the total size of the Study area ? Shouldn't that be the same under the blue, green and orange curve? Or is the difference compensated by omitted cells with 0% Built-up?
2. "Prior built-up is used as a constraint", does this imply that the total amount of Built up (i.e. the integral of x*c(x) ) should remain constant, which is clearly not the case ? 
3. Which Item(s) (full-path) did you use to make these curves ? I'll try to see then how the claim / constraint is violated.

**Comment by cjacobscrisioni** [comment]
/Analysis/Future/Indicators/BuiltUp_Percentages_Histogram already available in 2BURP main, I am testing alternate specifications in the Builtup_alloc_experiments branch

**Comment by MaartenHilferink** [comment]
Total build-up (see statistics->sums up to 2060) seems increasing with a reasonable pace.., are these the staggered increases?

![image](https://github.com/ObjectVision/2BURP/assets/2284361/4469f280-73a3-47b5-b122-3793c55e65e7)

**Comment by cjacobscrisioni** [comment]
The "staggering" (acknowledgement: this is hardly the right term) is in the preference of the model for specific density levels (the 6th, 12th, 18th, ... 48th percentage classes). Equally worrying is the u-shape of the graph (with a comparatively large amount of built-up in the 50% built-up class)

**Comment by cjacobscrisioni** [comment]
Reflection: the peaks on the multiples of 6 are presumably a consequence of the 6% maximum builtup addition for the case that a cell starts from 0 and does not contain the locally maximum value.

**Comment by cjacobscrisioni** [comment]
Overview of density plots, density changes, transition likelihoods in all continents
[Density plots, density changes, transition matrices.pptx](https://github.com/ObjectVision/2BURP/files/15454592/Density.plots.density.changes.transition.matrices.pptx)

**Comment by cjacobscrisioni** [comment]
I've extracted and stylized moving-up probabilities from the US transition matrix

Stylization included:
- making sure that increases and decreases are monotone (before 5%, after 15%, respectively)
- imposing that probabilities are reduced to the initial (zero) level after the 44% mark

[Moving_up_probabilities.xlsx](https://github.com/ObjectVision/2BURP/files/15472929/Moving_up_probabilities.xlsx)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/2BURP/assets/2284361/6dc46965-79cd-4f76-9242-4a85d5284085)

**Comment by cjacobscrisioni** [comment]
Current results (repulsion factor kept at constant 1f)

![image](https://github.com/ObjectVision/2BURP/assets/144823297/12025759-3c4c-406e-b921-9d2cd263f2f4)

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/2BURP/assets/2284361/c3c8bc50-d248-460e-bd70-6973b993eea8)

**Comment by cjacobscrisioni** [comment]
Nigeria (met balancing factor) 
![image](https://github.com/ObjectVision/2BURP/assets/144823297/148f7455-e92e-44e2-bd69-a8b1114a0e8c)

**Comment by cjacobscrisioni** [comment]
Nigeria, loglineair
![image](https://github.com/ObjectVision/2BURP/assets/144823297/065ef604-4e5b-4884-a21d-394c1fcd30ff)

**Comment by cjacobscrisioni** [comment]
Netherlands (absolute)
![image](https://github.com/ObjectVision/2BURP/assets/144823297/463b481c-2601-4f1a-9255-0e5f9e893928)

**Comment by cjacobscrisioni** [comment]
Netherlands (loglineair)
![image](https://github.com/ObjectVision/2BURP/assets/144823297/27fa9b1b-ae31-49f4-9f91-2baed6a1bbc2)

**Comment by cjacobscrisioni** [comment]
Netherlands (delta %builtup by 2100)
![image](https://github.com/ObjectVision/2BURP/assets/144823297/a5587652-6674-465e-864f-2a96ce738d22)

**Comment by cjacobscrisioni** [comment]
Nicaragua
![image](https://github.com/ObjectVision/2BURP/assets/144823297/e083f69f-2692-47a4-b536-0abf15d38055)

**Comment by cjacobscrisioni** [comment]
Nicaragua (loglineair)
![image](https://github.com/ObjectVision/2BURP/assets/144823297/2622ddab-0d46-47a0-b453-937fdfeda468)

**Comment by cjacobscrisioni** [comment]
Nicaragua (delta % builtup by 2100)
![image](https://github.com/ObjectVision/2BURP/assets/144823297/429e6b12-c307-4cf5-b9a2-3e0c0e617145)

Nicaragua reference year:
![image](https://github.com/ObjectVision/2BURP/assets/144823297/63b2f856-7308-4990-b678-1f0eca1787c1)

**Comment by cjacobscrisioni** [comment]
Weird patterns in Nicarague seem due to null suitabilities that translate into probabilities = 1

**Comment by cjacobscrisioni** [comment]
Weird patterns in Nicaragua due to insufficient catching of null exceptions in distance to cities.. recomputing.

**Comment by cjacobscrisioni** [comment]
Model results Nicaragua after suitability fix
![image](https://github.com/ObjectVision/2BURP/assets/144823297/6a10dc43-a533-4fff-8ba3-41717eab0540)

Loglinear
![image](https://github.com/ObjectVision/2BURP/assets/144823297/0b4a6469-af43-4354-90b5-6e33afaf2fa2)

**Comment by cjacobscrisioni** [comment]
Nigeria, met suitabilities fix:
![image](https://github.com/ObjectVision/2BURP/assets/144823297/66653be9-ce5f-4142-8c08-92aa4e2a083d)

Nigeria, met suitabilities fix, loglineair:
![image](https://github.com/ObjectVision/2BURP/assets/144823297/d5bd268d-38be-4ce5-93f8-eb6f75a79626)

Delta % builtup 2100 in Nigeria:

**Comment by MaartenHilferink** [comment]
![image](https://github.com/ObjectVision/2BURP/assets/2284361/59b20a37-4680-483e-a7df-0343ebbe8e06)

**Comment by cjacobscrisioni** [comment]
Nigeria plots (linear) after minor suitability fixes, making built-up discrete
![image](https://github.com/ObjectVision/2BURP/assets/144823297/535ee152-e963-4fc5-b0e3-f61fb1fde40b)

Nigeria loglinear
![image](https://github.com/ObjectVision/2BURP/assets/144823297/c864132f-9816-4510-acfb-3e70d2dcf84d)

Class sizes as share of total built-up (Nigeria)
![image](https://github.com/ObjectVision/2BURP/assets/144823297/bc52c5c8-294c-49db-9858-56a561201055)

**Comment by cjacobscrisioni** [comment]
Netherlands linear
![image](https://github.com/ObjectVision/2BURP/assets/144823297/ba79624a-a924-4481-8d2f-c6420607b303)

Netherlands loglinear
![image](https://github.com/ObjectVision/2BURP/assets/144823297/e748db53-752d-492e-8761-bd674e15432f)

**Comment by cjacobscrisioni** [comment]
Nicaragua (linear)
![image](https://github.com/ObjectVision/2BURP/assets/144823297/ce3e8504-5a35-4fac-a2e1-036529f2a18a)

Nicaragua (loglinear)
![image](https://github.com/ObjectVision/2BURP/assets/144823297/8ffe1b59-7bc6-4e15-8cf5-74e89827759e)

**Comment by jipclaassens** [comment]
Chris notes that there are changes between 2 days ago and yesterday and whether this is 'better'

2 days ago (Nigeria)
![image](https://github.com/ObjectVision/2BURP/assets/48675272/5a24d5dd-f2e8-4a4e-9b72-8a4be1b54e4c)


Yesterday:
![image](https://github.com/ObjectVision/2BURP/assets/48675272/677031ef-cf12-498d-aab7-3ffaa00e4bd4)
