### ISSUE TITLE
Investigate BU border issues and checkerboard patterns

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#57]

**Comment by cjacobscrisioni** [comment]
Checkerboard patterns
![image](https://github.com/ObjectVision/2BURP/assets/144823297/258a8ec8-219d-44db-a230-71938eaf7b49)

Border issues
![image](https://github.com/ObjectVision/2BURP/assets/144823297/349d85d6-b8ea-4f59-8ea6-880c60e037bd)

**Comment by jipclaassens** [comment]
There were null values, now fixed:



![Image](https://github.com/ObjectVision/2BURP/assets/48675272/2aed625a-116a-4966-868b-104467edc37b)
