### ISSUE TITLE
make RoundedState balanced per percentile and person

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/2BURP#63]
for BuiltUp (now with one roundoff_breakpoint per region)
for Population, based on the fractional /Analysis/Future/Allocate_Population/Y2030/NewState/Population

**Comment by jipclaassens** [comment]
Unbalanced 2030:


![Image](https://github.com/ObjectVision/2BURP/assets/48675272/0f1ab3be-f924-47a0-b024-58f9b6e95e5f)

Balanced 2030:


![Image](https://github.com/ObjectVision/2BURP/assets/48675272/29a3ed52-f581-4b12-b478-8a150c297365)
