### ISSUE TITLE
Presentation June 17th

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#66]
- Visualise change colour-coded (average year added?)
- some density plots
- some change maps for study areas
- show changes in DoU as a GIF

**Comment by cjacobscrisioni** [comment]
Context: material needed for update meeting with UN on 18/6. Deadline for presentation is 17/6. 

Just had a talk with Lewis who listed the requirements exhaustively:
- [ ] Built-up: density plots (per continent) 2020, 2060, 2100
- [ ] Built-up: zoomed maps with initial state, delta built-up fraction, final state, and average grid cell built-up age
- [ ] Population: density plots with adjusted bins (see 8de0be4..d4d36a9), without the zero class, bins well identifiable (per continent)
- [ ] Population: stacked bar chart with relative and absolute change per bin (per continent)
- [ ] Population: table with relative and absolute population change per bin
- [ ] Population: absolute population changes (zoomed in)
- [ ] Degree of urbanisation: stacked line graph of population change by degree 2 of degurbas (dynamic classification)
- [ ] Animations showing zoomed-in changes in degree of urbanisation

**Comment by jipclaassens** [comment]
![Image](https://github.com/ObjectVision/2BURP/assets/48675272/57fb10f8-5dbf-4474-8c30-4303dbdb20d8)

**Comment by jipclaassens** [comment]
![Image](https://github.com/ObjectVision/2BURP/assets/48675272/bc79ffe9-c332-46fa-8d84-478f8be215b8)



![Image](https://github.com/ObjectVision/2BURP/assets/48675272/ff9747da-3cc2-46e6-85fb-7c17dd86c89e)

**Comment by jipclaassens** [comment]
Europe
![image](https://github.com/ObjectVision/2BURP/assets/48675272/7c8f5b6f-d359-4d45-b32c-105d2de80002)

Africa
![image](https://github.com/ObjectVision/2BURP/assets/48675272/c87698bb-c3fc-486a-8dbd-e1c391135af9)

**Comment by jipclaassens** [comment]
Golf bewegingen komen voort uit de binsizes. Zie hier voor gelijke bin-sizes:
![image](https://github.com/ObjectVision/2BURP/assets/48675272/c5ff822d-ef53-4239-b497-1ed5865cb3b7)

**Comment by jipclaassens** [comment]
Met bins per 300, logarithmisch, afgekapt op 30000:

![image](https://github.com/ObjectVision/2BURP/assets/48675272/0239c138-a781-47da-8c33-66f9bbbcd074)

**Comment by jipclaassens** [comment]
Op verschilllende plekken op de curve:

![image](https://github.com/ObjectVision/2BURP/assets/48675272/ebd71fec-e962-41eb-8ef0-878e138c931a)
![image](https://github.com/ObjectVision/2BURP/assets/48675272/34ccada8-8a1e-4354-8a64-9df59b9ebb89)
![image](https://github.com/ObjectVision/2BURP/assets/48675272/6258a27a-b68e-4d19-a2ee-681fbde5bd9b)
![image](https://github.com/ObjectVision/2BURP/assets/48675272/b545f0ff-53ff-4718-b5d9-4b744c1b92ab)
![image](https://github.com/ObjectVision/2BURP/assets/48675272/13c1a54b-e00f-4541-b241-9c502146ae17)

**Comment by cjacobscrisioni** [comment]
Note: /Analysis/Future/Indicators/Population_perDoU is incredibly slow to compute

**Comment by cjacobscrisioni** [comment]
Some degree of urbanisation grids from Africa: 
![image](https://github.com/ObjectVision/2BURP/assets/144823297/66c0fd77-e679-4e77-ae9a-e5082745f410)
![image](https://github.com/ObjectVision/2BURP/assets/144823297/890df3fe-dc28-4f39-ad0f-54dafdc2476c)
![image](https://github.com/ObjectVision/2BURP/assets/144823297/53a6d570-1a66-4c69-91e0-4fa2e42f65c3)

**Comment by cjacobscrisioni** [comment]
I did find an issue with population totals in NL. See https://github.com/ObjectVision/2BURP/issues/67. Not sure if this is a glitch on my computer or a broader issue. Worth taking a look at.

**Comment by jipclaassens** [comment]
Updated request for June 18th by Lewis:
- BU/Pop/DoU for only South America and Africa
-
