### ISSUE TITLE
Logical flaw in population allocation approach exceptionally causes population total to exceed population claim?

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/2BURP#67]
When running the Netherlands I end up with a 114+ Million total population. 

The reason seems to be a logical flaw in the allocation process. 

In /Analysis/Future/Allocate_Population/Y2030/NewState/Population_in_New_BuiltUp_Area we allocate an absolute number people to new built-up developments, regardless of the total pool that we need to allocate. 

In case of high surrounding residential densities, the total population in /Analysis/Future/Allocate_Population/Y2030/NewState/Population_beforeAllocation exceeds the total population claim. 

This causes the /Analysis/Future/Allocate_Population/Y2030/NewState/RestClaim to default to zero. Subsequently we get a zero ScaleFactor_0. This ultimately yields a null in /Analysis/Future/Allocate_Population/Y2030/NewState/Population_Allocation/Iter_0/RescaleFactor

**Comment by cjacobscrisioni** [comment]
First shot on resolutions: 

- scalesum Population_in_New_BuiltUp_Area on Claim - sum(Reduced_Population), if the initial result exceeds Claim - sum(Reduced_Population). This would force only reallocation to new built-up areas.
- allow a negative initial scalefactor to fix a residual negative change.

Alternatively the scalesum could be done on maximally a fixed % of the Claim - sum(Reduced_Population)

**Comment by jipclaassens** [comment]
Reproduced, indeed the initial problem lies with /Analysis/Future/Allocate_Population/Y2030/NewState/Population_in_New_BuiltUp_Area which could exceed the claim.

Im experimenting with your suggestions

**Comment by jipclaassens** [comment]
- The scalesum, of course, solves the problem. However, this way, the whole claim is filled in newly built areas—everywhere a little bit. So, this way, we cannot allocate anything using suitability.
- This could also mean that we should reduce more (more than the 2x 2.5% reduction?). But then we would be reshuffling a lot of the population. Is this what we want? We would also not be adhering to the distribution that we wanted.
- Or we could rethink the way we fill up newly built areas. Maybe less? Maybe we can increase the search area further so smaller densities are used?

**Comment by cjacobscrisioni** [comment]
Expanding the search area is a bit of a compromise between expressiveness and wanted outcomes I suppose. I can think of valid arguments to keep the search area small (Tobler's first law) but there are only pragmatic arguments to increase it. 

Higher reductions are unattractive (and they reduce the amount of cases in which this is an issue, but do not make a guaranteed fix)

Can we find an argument to say that a fixed % of the population pool ends up in newly developed area? We could scalesum on say maximally 75% of the population pool. Maybe even less. This would still allow for some reshuffling in existing urban areas.

**Comment by jipclaassens** [comment]
Good points. Is this something to discuss this afternoon with Lewis, or should we bring it up earlier so we can still prepare his figures for tomorrow?

**Comment by jipclaassens** [comment]
Na edits 17.30u

Africa Claim realisation:

Kaap Verdie
![Image](https://github.com/ObjectVision/2BURP/assets/48675272/82283704-a92d-4de9-b23f-177cb9043efc)


167 ==  seychelle
![Image](https://github.com/ObjectVision/2BURP/assets/48675272/7975f7d1-ca33-46b6-93ff-74c1d8ec2815)

**Comment by jipclaassens** [comment]
We needed to correct for Null values in the scale factor and rescale factor:

```
Template Population_Allocation_T
{
	attribute<float32>       ScaleFactor                  (ClaimRegion);
	///
	attribute<Person>        Population               (CompactedDomain) := min_elem(ScaleFactor[Region_rel] * Suitability/Population * Room_for_Population_Normalised, Room_for_Population);
	attribute<Person>        Population_rounded       (CompactedDomain) := int32(Population)[Person]; //we round here, to omit fractional people which can then reallocated in the next iter.
	attribute<Person>        Realisation                  (ClaimRegion) := sum(Population_rounded, Region_rel);
	attribute<float32>       RescaleFactor                (ClaimRegion) := RestClaim / Realisation; // We need to correct the scale factor to accomodate left over claims.
	attribute<float32>       ScaleFactor_new              (ClaimRegion) := IsNull(ScaleFactor) || IsNull(RescaleFactor) ? 0f : ScaleFactor * RescaleFactor;
}
````

Because the ScaleFactor could be 0, if the restclaim was 0. 
And the RescaleFactor could be null if the Realisation was 0, and the reaslisation could be 0, if the scalefactor is 0.

**Comment by jipclaassens** [comment]
Furthermore, there were Null-values in the suitability since the FloodProne dataset was null in area's such as Cabo Verde. Which resulted in null Sum_Suitability for the whole FA. 
Now hacked with a makedefined(readdata, 0b).

**Comment by jipclaassens** [comment]
Close enough

![Image](https://github.com/ObjectVision/2BURP/assets/48675272/4d695d59-fae7-457b-8b38-688fe1cd0c3a)
