### ISSUE TITLE
Do we want to allow new pop in the ocean?

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#70]
![Image](https://github.com/ObjectVision/2BURP/assets/48675272/eae42451-069a-430a-9570-2168fca22aec)

**Comment by jipclaassens** [comment]
Omit ocean cells from compacted domain?

**Comment by cjacobscrisioni** [comment]
If we would factor in sea level rise this becomes a tricky question (and the endogeneity issue may drive one to the brink) but in the spirit of good pragmatics I advocate we entirely drop grid cells that have no land.

**Comment by cjacobscrisioni** [comment]
Just pushed a fix so that grid cells need to contain some land (or built-up cells, or population, just to check for exceptions), see 5be3154..baa61b4
