### ISSUE TITLE
Insufficient room for population in some functional areas

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/2BURP#71]
/Analysis/Future/Allocate_Population/Y2030/NewState/Check_for_enough_suitable_locations is used as an integrity check in the population scaling. It depends on having a sufficient number of locations with suitability > 0.

In eg Faya-Largeau (functional area in Chad, Africa) the number of cells with suitability > 0 is less than the restclaim. In fact sum_room_for_population is 56569, restclaim is 67012. This throws an error.  Seems to be caused by sizeable population growth in combination with limited suitable locations. 

Fundamentally, is it necessary to ensure that restclaim <= suitable cells? The implication is that we do not allow more than 1 person added on average, correct?

**Comment by jipclaassens** [comment]
Well, I think you are confusing the `number of suitable cells >= restclaim` with `sum_room_for_pop >= restclaim`.
The latter means to ensure that the claims could theoretically be reached.

**Comment by cjacobscrisioni** [comment]
> Well, I think you are confusing the `number of suitable cells >= restclaim` with `sum_room_for_pop >= restclaim`. The latter means to ensure that the claims could theoretically be reached.

Fair point! ... does not resolve the problem though. I think I will try to adjust the Pop_r settings, these may be too restrictive for high-growth conditions

**Comment by jipclaassens** [comment]
Haha, nice touch to only change the title.

On topic: if you do not have this check, you could reach the maximum without knowing it. And thus not meeting full claim realisation. Then, thinking you are done, it might be a model error to have a too-strict maximum allowed pop or too-low suitability.

**Comment by cjacobscrisioni** [comment]
> Haha, nice touch to only change the title.
> 
> On topic: if you do not have this check, you could reach the maximum without knowing it. And thus not meeting full claim realisation. Then, thinking you are done, it might be a model error to have a too-strict maximum allowed pop or too-low suitability.

Fully agreed that the integritycheck is useful!
