### ISSUE TITLE
Remove empty BU after X years

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#76]
Do we want this?

We have an absolute claim for BU, if we remove empty BU. How much builtup do we allocate in the future?

**Comment by jipclaassens** [comment]
Yes, we could do it like in LUISA (Maarten pointed me towards this option), where we register abandoned residential areas, which could be easier to repopulate than natural/agricultural land.

**Comment by jipclaassens** [comment]
No, that won't work. Since we allocate first BU for all years and then population. So I've now implemented it in the indicators. 

/Analysis/Future/Indicators/Prep/BuiltUp_Residential_Area_Without_Abandoned

**Comment by cjacobscrisioni** [comment]
Indeed marking it as empty BU would be preferrable. quick check that may be necessary: how much urban land without population do we have in 2020? Those may already be abandoned or function as e.g. holiday homes.

**Comment by MaartenHilferink** [comment]
Alternatief: bereken Avg BU weighted to pop := BU*pop / sum(pop*pop)
