### ISSUE TITLE
Experiment with other pop reduction values

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#77]
bv 1% ipv 2.5%

Indicators:
- area per DoU (@cjacobscrisioni doet eerst #78 hiervoor)
- pop dens per DoU

**Comment by jipclaassens** [comment]
Europe, difference proportional and absolute reduction:

Density:
1%
![image](https://github.com/user-attachments/assets/a6e969fc-3895-47fa-96fa-3e218855f034)

2.5%
![image](https://github.com/user-attachments/assets/a03bbfb0-8e71-4fc2-9c10-05d55bb0e695)

Land area:
1%
![image](https://github.com/user-attachments/assets/d3dc2215-29b2-4625-b6fa-9309715580bd)

2.5%
![image](https://github.com/user-attachments/assets/dd93be42-7fce-40a2-8ebe-fb7f8aace9af)

**Comment by jipclaassens** [comment]
> @jipclaassens , these look as expected. But Europe is fairly well-behaved as is. Can you possibly also make these for e.g. Africa?

running 1%, 2.5% and 5% as we speak.

**Comment by jipclaassens** [comment]
Africa, difference proportional and absolute reduction:

Density:
1%
![image](https://github.com/user-attachments/assets/57b0d098-4361-4182-b83e-81da6186ea12)

2.5%
![image](https://github.com/user-attachments/assets/55342a94-8582-40b5-ad67-d109d5db45f5)

5%
![image](https://github.com/user-attachments/assets/4693b794-fb9b-4cf8-bdf7-ddaa47ea96ff)


Land area:
1%
![image](https://github.com/user-attachments/assets/d98e712d-72c7-4c2a-8387-c46ff594a315)

2.5%
![image](https://github.com/user-attachments/assets/b2bca8f1-504b-4f8b-b1a7-5760ff9220ef)

5%
![image](https://github.com/user-attachments/assets/cef25bce-2b4c-48e6-8c51-d249b5890458)

**Comment by jipclaassens** [comment]
It seems that 1% or 2.5% doesn't do so much. Whereas 5% has more impact, do you concur? @cjacobscrisioni

**Comment by jipclaassens** [comment]
excel file

**Comment by cjacobscrisioni** [comment]
Looking at the absolute population densities in the Excel sheets, the 1% and 2.5% results are completely identical (just rounded differently here and there). Are you absolutely certain this is not an error, so that we can conclude that lowering pop reductions below 2.5% does not have *any* effect on densities?

**Comment by jipclaassens** [comment]
Sharp, let me see

**Comment by jipclaassens** [comment]
Updated

**Comment by cjacobscrisioni** [comment]
Thanks!!!! On the one hand, bigger percentages lead to bigger shifts in typologies (more new urban area specifically), on the other hand the loss of densities in urban areas is slightly less with bigger percentages. All in all, not the major impact we expected? 

Follow-up question: what if we look at changes in population densities by 2020 degree of urbanisation?

**Comment by jipclaassens** [comment]
Africa, with DoU 2020:
1%
![image](https://github.com/user-attachments/assets/2490b9ff-9f87-4287-ba36-89b50841825e)

2.5%
![image](https://github.com/user-attachments/assets/d669ff7a-26df-4dc7-891a-8aba37b86c8a)

5%
![image](https://github.com/user-attachments/assets/a069dbfb-e401-4ee2-9521-a136d56bef60)

**Comment by jipclaassens** [comment]
[Analyse PopReduction Parameters_20240722.xlsx](https://github.com/user-attachments/files/16347892/Analyse.PopReduction.Parameters_20240722.xlsx)

**Comment by jipclaassens** [comment]
Conclusion:
- the effect of 1% and 2.5% is quite similar. 5% not as much as we expected.
- in pre-existing urban areas, population densities increase, so the drop in urban densities is not an artefact of population reduction rules.
