### ISSUE TITLE
Experiment with Pop_ShareOfRestclaim_Prefers_newBU

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#82]
Edit here:
`/Analysis/Future/Allocate_Population/Y2030/NewState/Pop_in_New_BU_Area_Augm_Teller`

- not much effect on density
- but quite some effect on total population; the population in the urban centre/dense/semi-dense are all increasing with decreasing share in newBU. 

Rwanda/Tanzania/Kenya
100%:
![image](https://github.com/user-attachments/assets/72b8e515-6dd6-432d-b367-1c16c6c197c4)

75%
![image](https://github.com/user-attachments/assets/fead0e92-74ac-4bd4-bec8-26bebcfea11b)

50%
![image](https://github.com/user-attachments/assets/e3bd1c0c-57dd-47ec-817c-d9317d5ecec2)

100%
![image](https://github.com/user-attachments/assets/20bfd165-d5be-4836-aa4a-f769a259c640)

75%
![image](https://github.com/user-attachments/assets/ed087f6c-0394-4e33-bf05-74126a8bcfa2)

50%
![image](https://github.com/user-attachments/assets/005d4aa8-9d12-4e7a-a83d-5e769b9d4164)

**Comment by jipclaassens** [comment]
Land area
100%
![image](https://github.com/user-attachments/assets/cc5b3a1e-7585-42fa-9333-e26d47c3e4d8)

75%
![image](https://github.com/user-attachments/assets/7184d256-84bd-40bd-9bc3-d48a1b4f69af)

50%
![image](https://github.com/user-attachments/assets/814bcb2b-6a0c-4ca2-b9ba-89cd6bb73570)

**Comment by jipclaassens** [comment]
[Analyse PopShareInBU Parameters_20240723.xlsx](https://github.com/user-attachments/files/16350670/Analyse.PopShareInBU.Parameters_20240723.xlsx)

**Comment by cjacobscrisioni** [comment]
Interesting!

With lower a lower fraction of population, we see more land allocated to urban centres, with overall more people in them. Given that excessive urban centres (Egypt, Burundi) are a key concern, I think it is safe to say we ought to keep this parameter at 100%. Reassuring in a way, as thus the only limitation to allocation is a technical restriction.

More broadly, this issue and #77 both report on experiments in which ad-hoc parameters were adjusted to find whether they are helpful in maintaining densities and limiting expansion of urban centres. On both counts we have seen fairly limited effects in aggregate outcomes. 

My conclusion is that, if we want to adjust our results, we best do so by tackling moving-up probabilities or the claims for built-up land. Through the balancing mechanism in conjunction with the m-u-p, suitabilities are potentially of limited import for aggregate results.
