### ISSUE TITLE
Adapt built-up value distributions in case of unprecedented built-up expansion

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/2BURP#84]
We have a number of cases where, due to extreme population growth, the amount of urban expansion will be considerable. 

In eg Egypt and Rwanda this leads to the formation of implausibly large ultra-cities, in conjunction with current MUPPY (Moving-Up Percentage ProbabilitY). The latter tend to nudge urban expansion in grid cells that have low to mid-range built-up levels. 

The projections cannot be adapted. We may need to somehow factor in that, in cases where space is under pressure, urban expansion will be contained towards grid cells with high built-up densities.

**Comment by cjacobscrisioni** [comment]
Option one - adapt the MUPPY matrix dynamically by available space. Equation would take this form: 

Available space = av = 1 - (Built-up claim / area in compacted domain)
Weight = W = (P / A) - P, with P being the percentage class (0 to 50)
Weighted MUP = WMUP = max(W, 1) * MUP, with the max(W, 1) is there solely to account for situations in which the weight is zero.

With decreasing av this would lead to an upward shift of weighted MUPPY on the righthand side (see graph below for weighted MUPPY with increasing av)

![image](https://github.com/user-attachments/assets/53500e36-14a8-4339-8150-48052f83f7d6)

I think we could plug this in without having to scalesum the WMUPPY values, as there is a scalesum further down the line anyway. The average arithmetic av in Europe is ~0.986 at least for 2030, so overall the effect would be quite limited at least in Europe.

**Comment by cjacobscrisioni** [comment]
@MaartenHilferink, I've added you here as you proposed an alternative approach to dealing with situations such as Rwanda. Pls feel free to add your proposal (and edit the title if necessary :) )

**Comment by jipclaassens** [comment]
@cjacobscrisioni, this sounds interesting. Do I understand correctly that this means that if space is limited, the MUPPY increases the percentages? And thus creates higher density cities? 

While this sounds theoretically good, it has little effect in Europe because there might be limited space and a low claim?

I am curious to see how this behaves in high-demand, low-supply areas.

Btw, @MaartenHilferink is on holiday for the next three weeks.

**Comment by cjacobscrisioni** [comment]
Hi Jip yes this should adapt muppys towards higher density built up in case of space limitations. Might slightly different increase buillt up shares in some functional areas in Europe, should have a large impact in eg Rwanda and Pakistan Sent from Android deviceOp 12 aug. 2024 11:26 schreef Jip Claassens ***@***.***>:
@cjacobscrisioni, this sounds interesting. Do I understand correctly that this means that if space is limited, the MUPPY increases the percentages? And thus creates higher density cities?
While this sounds theoretically good, it has little effect in Europe because there might be limited space and a low claim?
I am curious to see how this behaves in high-demand, low-supply areas.
Btw, @MaartenHilferink is on holiday for the next three weeks.

**Comment by cjacobscrisioni** [comment]
First results, running Africa with:

Static MUPPYs
![static_muppys_run_aug24](https://github.com/user-attachments/assets/3cf0a0c3-070a-4cc1-92a0-3e865d306935)

Dynamic MUPPYs, W = max_elem[(P / A) - P, 1]
![dynamic_muppys_linear_30aug24](https://github.com/user-attachments/assets/aef6f2b2-5877-41fd-a71f-c9efb5de910c)

Dynamic MUPPYs, W = max_elem[(P / A^2) - P, 1]
![dynamic_muppys_quadratic_30aug24](https://github.com/user-attachments/assets/159dc2b5-65b4-44f1-9765-d452f91d3a5e)

Slightly contracted urban patterns with more stringent weights, not as much as I anticipated though. The max_elem(..., 1) may be to 'soft' on low values of P

**Comment by cjacobscrisioni** [comment]
Adapted the weighting so that Weighted MUP = WMUP = (W + 1) * MUP. This seems to have a slightly more balanced effect on the built-up distribution (limited visual checks only so far). In terms of effect, this specification (with A^1) is more restrictive than the first linear take on A, less restrictive than the first power take on A.

**Comment by cjacobscrisioni** [comment]
Weighted MUPPYs with A^2 seem the most convincing...

Densities:
![Image](https://github.com/user-attachments/assets/d037d82b-b0ee-4329-bc7c-e268d744f534)

Map of Burundi:
![Image](https://github.com/user-attachments/assets/ceb5fbc4-a2b0-425c-a4d7-5f4a4d8b4f80)

I propose we use the final approach, ie
W = (P / A^2) - P
WMUP = (W + 1) * MUP
