### ISSUE TITLE
Investigate abandonement

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#86]
also try bu rounded and pop threshold of 10 persons

**Comment by jipclaassens** [comment]
UIt meeting van 28 okt:
The share of cells with at least 1 person that empty out after a decade: analysis per decade and world region

**Comment by jipclaassens** [comment]
related #76

**Comment by cjacobscrisioni** [comment]
Abandonment allyears indicator added and committed, not yet pushed while waiting for mollweide conversion. Results depend on population percentage reduction params, with higher reduction leading to faster abandonment, and also with faster abandonment in case relatively more weight is given to absolute reductions (when absolute and proportional reductions are unbalanced. 

Results given balanced 1% reductions:
![Image](https://github.com/user-attachments/assets/1ddff88f-98d1-44f3-a168-90ecceed3bc6)
![Image](https://github.com/user-attachments/assets/113e98fd-3ee5-49b2-a782-ab345d0dde72)
![Image](https://github.com/user-attachments/assets/366ffc6c-fc86-46f8-a4bd-17b64332d6fe)
![Image](https://github.com/user-attachments/assets/9ce162a1-4483-4d2e-9a0e-09a2c46ea570)
![Image](https://github.com/user-attachments/assets/444e4c0e-b2a6-4c6f-9f87-d27814097c9a)
![Image](https://github.com/user-attachments/assets/9a7d294e-1eec-4d45-be9f-3c44d9be6bc6)
