### ISSUE TITLE
Verify relation between built-up per capita and pop density loss

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/2BURP#91]

**Comment by jipclaassens** [comment]
![image](https://github.com/user-attachments/assets/65fe880a-626a-40bf-9563-f42f388e56d5)

**Comment by cjacobscrisioni** [comment]
From Teams chat:

Density losses vs initial densities
![image](https://github.com/user-attachments/assets/8c9027c4-d080-470f-85af-3c50c11e21b5)

Density change vs bucap change
![image](https://github.com/user-attachments/assets/141c9200-e7c4-4e96-aa50-6e9a2d918f63)

Regression results
<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>



  | Africa | Asia | Europe | North Am | South Am
-- | -- | -- | -- | -- | --
 
Change in Bucap | 0.010 | -0.051*** | -0.122*** | -0.117*** | -0.058***
  | (0.011) | (0.006) | (0.018) | (0.022) | (0.022)
  |   |   |   |   |  
Bucap 2020 | 0.001 | -0.001*** | 0.00005 | 0.0004 | -0.003***
  | (0.0005) | (0.0003) | (0.0005) | (0.0004) | (0.001)
  |   |   |   |   |  
Initial urban density | -0.00003*** | -0.00003*** | 0.00002** | -0.00002 | -0.00005***
  | (0.00000) | (0.00000) | (0.00001) | (0.00001) | (0.00001)
  |   |   |   |   |  
Constant | 0.946*** | 1.147*** | 0.988*** | 1.161*** | 1.388***
  | (0.057) | (0.042) | (0.086) | (0.096) | (0.129)
  |   |   |   |   |  
 
Observations | 247 | 345 | 142 | 94 | 78
R2 | 0.340 | 0.332 | 0.363 | 0.641 | 0.428




</body>

</html>
