### ISSUE TITLE
map of new urban cells in 2030 and why they became urban

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/2BURP#93]

**Comment by jipclaassens** [comment]
new urban cluster tussen 2020 en 2030:
![Image](https://github.com/user-attachments/assets/6a6808fb-15af-44ef-a0c7-d516412f3acf)

2020
![Image](https://github.com/user-attachments/assets/ab044c93-efcf-497d-86a0-e1586bf973cf)

2030
![Image](https://github.com/user-attachments/assets/34fb210b-13a6-412a-8d14-f3610d0cad28)

Oftewel Bussem verandert van een dense urban cluster naar een urban centre.

**Comment by jipclaassens** [comment]
in 2020 en 2030
alle cellen zijn > 1500 pop/km2
alle cellen zijn > 0.5 BU share

in 2020 is group pop = 49515 persons
in 2030 is group pop = 53634 persons

Min_Total_Pop voor een urban cluster is 50k.

**Comment by jipclaassens** [comment]
Nieuwe cellen aan de rand van amsterdam:
![Image](https://github.com/user-attachments/assets/c09a07ba-b0bf-4e97-b34f-95121591c4d7)

Wordt toegevoegd door MedianFiltering.

**Comment by jipclaassens** [comment]
New result with v7 

![image](https://github.com/user-attachments/assets/67aef853-b818-4a03-96a6-c20bd45b13b4)

**Comment by cjacobscrisioni** [comment]
In voorgaande runs (v6, major difference with graph above is that the graph above contains degurba fixes in #93)

![image](https://github.com/user-attachments/assets/784d8461-3b89-4b5b-a191-0130c7970dbf)

**Comment by jipclaassens** [comment]
Mogelijke verklaringen:
- in het eerste allocatie jaar wordt een soort inhaalslag gemaakt naar 'onze' meest geschikte locaties. 
- discretisering waardoor de bevolking meer clustert.
