### ISSUE TITLE
run with zero claims for built-up and population to see dynamics and (de)convergence to a steady state.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/2BURP#95]

**Comment by jipclaassens** [comment]
Run with claims of FUA sum of 2020.

![Image](https://github.com/user-attachments/assets/cb1afc66-a17b-486d-b009-867fc62e38f4)

**Comment by jipclaassens** [comment]
Rounding aangepast naar één keer na allocatie per tjidstap, met een random factor:

![Image](https://github.com/user-attachments/assets/f3e57723-7ead-4eb2-94b6-80704dc12754)
![Image](https://github.com/user-attachments/assets/0b27dcad-8e5c-4c0d-8a6e-2df60b8520e5)
![Image](https://github.com/user-attachments/assets/ae5fefb4-7588-4043-b0b1-bf10a352eacd)

**Comment by cjacobscrisioni** [comment]
Population per DoU and population density per DoU for Africa, same conclusions:
![image](https://github.com/user-attachments/assets/08923953-2918-4633-b142-94f76a995e48)
![image](https://github.com/user-attachments/assets/26e2b868-a451-4678-8845-4a741fdec988)
