### ISSUE TITLE
Faulty Urban Centre identification in DoU

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/2BURP#97]
De Biesbosch wordt een nieuw Urban cluster in 2030 tov 2020.
![Image](https://github.com/user-attachments/assets/5193e613-9087-4059-8c59-d204d5bbc4f7)

Waarom?

Om mee te dingen voor een urban cluster moet er een minimale pop density of BU share gehaald worden. Er is meestal geen pop:
![Image](https://github.com/user-attachments/assets/28468ec9-dfee-4ae4-bcd0-4e0abc010458)

Maar wel BU:
![Image](https://github.com/user-attachments/assets/d975c437-f421-4539-adf3-2e8affcbd7e9)

Deze is namelijk telkens 1, oftwel 100% van de cell bebouwd:
![Image](https://github.com/user-attachments/assets/ce1a166d-8a93-4ac6-9a34-18170f91e358)

Hoe komen we aan deze waarde?
`BU_Total_Area / xland_den_1`
Hierin is
`BU_Total_Area ==  6.17615E-11 km2`
`xland_den_1 ==  6.17615E-11 km2`

Dus het gaat fout in xland_den_1. Deze wordt zo bepaald:

```
attribute<km2>               xland_den_1     (domain) := switch(
	case(xland_zero  &&  bu_above_zero && pop_above_zero, BuiltUp_Total_Area_domain),  // xland_den(idx) = xbu(idx);
	case(xland_zero  && !bu_above_zero && pop_above_zero, min_elem(max_elem(Parameters/P_FixLandShareBU, Population_domain[float32] * Parameters/P_FixLandSharePOP), 1[km2])), // xland_den(idx) = min(max(P_FixLandShareBU,xpop(idx)*P_FixLandSharePOP),1)
	case(!xland_zero && xland < BuiltUp_Total_Area_domain, BuiltUp_Total_Area_domain), // idx = xland_den(:)<xbu(:) & xland_den(:)>0; {	xland_den(idx) = xbu(idx);}
	case(!xland_zero && !bu_above_zero && (xland / Population_domain) < Parameters/P_FixLandSharePOP, min_elem(max_elem(Parameters/P_FixLandShareBU, Population_domain[float32]*Parameters/P_FixLandSharePOP),1[km2])),
	xland);
```

Hier in zijn:
```
xland ==  6.17615E-11 km2
xland_zero == false
bu_above_zero == true
pop_above_zero == false
```

Dus de else wordt hier gebruikt en dus wordt xland_den_1 gelijk aan xland en dus BU_Total_Area.

**Comment by jipclaassens** [comment]
Misschien moeten we een drempel waarde op deze BU area zetten? Minimaal 100m2 ofzo?

**Comment by jipclaassens** [comment]
Water fractie bepaling klopte niet:

Was:
```
attribute<uint32>  Fraction_InlandWater0  (domain) := sum(IsInlandWater[uint32], domain_sub/domain_rel);
attribute<uint32>  Fraction_InlandWater   (domain) := ((Fraction_InlandWater0[float32] / 36f) * 100f)[uint32];

attribute<uint32>  Fraction_Water0        (domain) := sum(IsWater[uint32], domain_sub/domain_rel);
attribute<uint32>  Fraction_Water         (domain) := ((Fraction_Water0[float32] / 36f) * 100f)[uint32];
```

Moet zijn, dit want er zitten 100 subdomain cellen in een gridcel, niet 36...
```
attribute<uint32>  Fraction_InlandWater  (domain) := sum(IsInlandWater[uint32], domain_sub/domain_rel);

attribute<uint32>  Fraction_Water        (domain) := sum(IsWater[uint32], domain_sub/domain_rel);
```

**Comment by jipclaassens** [comment]
Dit kan wel impact hebben op onze resultaten. Dit heeft effect cellen met relatief flink wat water, en die BU of Pop bevatten.

**Comment by cjacobscrisioni** [comment]
Pfoeh dank voor dit uitzoekwerk Jip! De huidige implementatie is mijn interpretatie van Marcello's OG degurba scripts. Ik ben net nog een keer door de originele scripts heengegaan maar kan niet terughalen waar die 36 vandaan zou moeten komen. Ik gok dat die 36 een typo is of een brainfart. In grote lijnen zal dat weinig uitmaken gok ik, maar in dit soort details dus duidelijk wel :)

**Comment by jipclaassens** [comment]
@cjacobscrisioni nou maanden geleden kwam ik erachter dat we 5 arcsec als subdomain grid gebruikte wat eingelijk 3 arcsec moest zijn. Dit heb ik toen aangepast. Maar helaas was die 36 hardcoded. Nu heb ik er params voor gebruikt.

**Comment by cjacobscrisioni** [comment]
betekend dit dat de 2030 bump in degurba's nu voltooid verleden tijd is?

**Comment by jipclaassens** [comment]
@cjacobscrisioni welke bump bedoel je nu precies? of juist die trend breuk? Welk item moet ik hiervoor checken?

**Comment by cjacobscrisioni** [comment]
die eenmalige omhoogschieter in pop per degurba in 2030. Goed te zien bijvoorbeeld in Europa.

**Comment by jipclaassens** [comment]
eehm, ik zie die niet. En ook niet in figuren van jullie van vorige week. Welk figuur bedoel jij precies?

![Image](https://github.com/user-attachments/assets/a708ba59-f611-4bb0-8714-77c8b215c94b)

**Comment by cjacobscrisioni** [comment]
Uit de slides die Lewis aan de UN liet zien....

Hier in Europa een beetje te zien:
![image](https://github.com/user-attachments/assets/d1d318c7-08da-4b62-b51e-84b85669886d)

In Afrika juist een dip:
![image](https://github.com/user-attachments/assets/99ab8186-499f-418e-bc09-432283dd9fe6)

**Comment by cjacobscrisioni** [comment]
![image](https://github.com/user-attachments/assets/82cf54e5-96ed-4fc6-8951-f1c748969bef)
