### ISSUE TITLE
Look into better integration with GHS-POP timeseries

### ISSUE THREAD

**Issue by cjacobscrisioni** [ObjectVision/2BURP#98]
There are a number of discrepancies between GHS-POP and 2BURP projections. Key issues to look into (at a later stage):

- discretisation increases noise and differences with GHS-POP. The reason to do this is expected leakage to low population fractions. What are the modelling implications of not making population discrete?

- discretisation also seems to cause sizeable displacement of population (from dispersed population to clusters). Can we reduce displacement when creating a discrete population grid? For example by combining suitbility with a potential of the rounded-down population fractions.
 
- To my best knowledge, population allocation in non-builtup areas is allowed. Are we allocating population in non-builtup?
 
- Conversion from lat/lon to equal area also causes noise. What are the costs of modelling Mollweide equal area instead of lat/lon?

**Comment by jipclaassens** [comment]
punt 3:
```attribute<Person> MaxAllowed_Population (CompactedDomain) := MaxAllowed_Population_Density * NewState_BuiltUp/BuiltUp_Residential_Area;```

**Comment by jipclaassens** [comment]
punt 2:
ondervangen door een nth_element op de initial pop map toe te passen en na allocatie opnieuw.

**Comment by jipclaassens** [comment]
punt 4:
#108
